// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: billing.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBillingServiceGetAccount = "/billing.v1.BillingService/GetAccount"
const OperationBillingServiceGetStatsMonth = "/billing.v1.BillingService/GetStatsMonth"
const OperationBillingServiceGetStatsSummary = "/billing.v1.BillingService/GetStatsSummary"
const OperationBillingServiceGetStatsToday = "/billing.v1.BillingService/GetStatsToday"
const OperationBillingServiceListRecords = "/billing.v1.BillingService/ListRecords"
const OperationBillingServiceRecharge = "/billing.v1.BillingService/Recharge"

type BillingServiceHTTPServer interface {
	// GetAccount 获取账户资产信息 (余额 + 剩余配额)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountReply, error)
	// GetStatsMonth 获取本月调用统计
	GetStatsMonth(context.Context, *GetStatsMonthRequest) (*GetStatsReply, error)
	// GetStatsSummary 获取汇总统计（所有服务）
	GetStatsSummary(context.Context, *GetStatsSummaryRequest) (*GetStatsSummaryReply, error)
	// GetStatsToday 获取今日调用统计
	GetStatsToday(context.Context, *GetStatsTodayRequest) (*GetStatsReply, error)
	// ListRecords 获取消费流水
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsReply, error)
	// Recharge 发起充值 (返回支付链接)
	Recharge(context.Context, *RechargeRequest) (*RechargeReply, error)
}

func RegisterBillingServiceHTTPServer(s *http.Server, srv BillingServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/billing/account", _BillingService_GetAccount0_HTTP_Handler(srv))
	r.POST("/api/v1/billing/recharge", _BillingService_Recharge0_HTTP_Handler(srv))
	r.GET("/api/v1/billing/records", _BillingService_ListRecords0_HTTP_Handler(srv))
	r.GET("/api/v1/billing/stats/today", _BillingService_GetStatsToday0_HTTP_Handler(srv))
	r.GET("/api/v1/billing/stats/month", _BillingService_GetStatsMonth0_HTTP_Handler(srv))
	r.GET("/api/v1/billing/stats/summary", _BillingService_GetStatsSummary0_HTTP_Handler(srv))
}

func _BillingService_GetAccount0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceGetAccount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccount(ctx, req.(*GetAccountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAccountReply)
		return ctx.Result(200, reply)
	}
}

func _BillingService_Recharge0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RechargeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceRecharge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Recharge(ctx, req.(*RechargeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RechargeReply)
		return ctx.Result(200, reply)
	}
}

func _BillingService_ListRecords0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceListRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRecords(ctx, req.(*ListRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRecordsReply)
		return ctx.Result(200, reply)
	}
}

func _BillingService_GetStatsToday0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStatsTodayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceGetStatsToday)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStatsToday(ctx, req.(*GetStatsTodayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStatsReply)
		return ctx.Result(200, reply)
	}
}

func _BillingService_GetStatsMonth0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStatsMonthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceGetStatsMonth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStatsMonth(ctx, req.(*GetStatsMonthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStatsReply)
		return ctx.Result(200, reply)
	}
}

func _BillingService_GetStatsSummary0_HTTP_Handler(srv BillingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStatsSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingServiceGetStatsSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStatsSummary(ctx, req.(*GetStatsSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStatsSummaryReply)
		return ctx.Result(200, reply)
	}
}

type BillingServiceHTTPClient interface {
	// GetAccount 获取账户资产信息 (余额 + 剩余配额)
	GetAccount(ctx context.Context, req *GetAccountRequest, opts ...http.CallOption) (rsp *GetAccountReply, err error)
	// GetStatsMonth 获取本月调用统计
	GetStatsMonth(ctx context.Context, req *GetStatsMonthRequest, opts ...http.CallOption) (rsp *GetStatsReply, err error)
	// GetStatsSummary 获取汇总统计（所有服务）
	GetStatsSummary(ctx context.Context, req *GetStatsSummaryRequest, opts ...http.CallOption) (rsp *GetStatsSummaryReply, err error)
	// GetStatsToday 获取今日调用统计
	GetStatsToday(ctx context.Context, req *GetStatsTodayRequest, opts ...http.CallOption) (rsp *GetStatsReply, err error)
	// ListRecords 获取消费流水
	ListRecords(ctx context.Context, req *ListRecordsRequest, opts ...http.CallOption) (rsp *ListRecordsReply, err error)
	// Recharge 发起充值 (返回支付链接)
	Recharge(ctx context.Context, req *RechargeRequest, opts ...http.CallOption) (rsp *RechargeReply, err error)
}

type BillingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBillingServiceHTTPClient(client *http.Client) BillingServiceHTTPClient {
	return &BillingServiceHTTPClientImpl{client}
}

// GetAccount 获取账户资产信息 (余额 + 剩余配额)
func (c *BillingServiceHTTPClientImpl) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...http.CallOption) (*GetAccountReply, error) {
	var out GetAccountReply
	pattern := "/api/v1/billing/account"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBillingServiceGetAccount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStatsMonth 获取本月调用统计
func (c *BillingServiceHTTPClientImpl) GetStatsMonth(ctx context.Context, in *GetStatsMonthRequest, opts ...http.CallOption) (*GetStatsReply, error) {
	var out GetStatsReply
	pattern := "/api/v1/billing/stats/month"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBillingServiceGetStatsMonth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStatsSummary 获取汇总统计（所有服务）
func (c *BillingServiceHTTPClientImpl) GetStatsSummary(ctx context.Context, in *GetStatsSummaryRequest, opts ...http.CallOption) (*GetStatsSummaryReply, error) {
	var out GetStatsSummaryReply
	pattern := "/api/v1/billing/stats/summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBillingServiceGetStatsSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStatsToday 获取今日调用统计
func (c *BillingServiceHTTPClientImpl) GetStatsToday(ctx context.Context, in *GetStatsTodayRequest, opts ...http.CallOption) (*GetStatsReply, error) {
	var out GetStatsReply
	pattern := "/api/v1/billing/stats/today"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBillingServiceGetStatsToday))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRecords 获取消费流水
func (c *BillingServiceHTTPClientImpl) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...http.CallOption) (*ListRecordsReply, error) {
	var out ListRecordsReply
	pattern := "/api/v1/billing/records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBillingServiceListRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Recharge 发起充值 (返回支付链接)
func (c *BillingServiceHTTPClientImpl) Recharge(ctx context.Context, in *RechargeRequest, opts ...http.CallOption) (*RechargeReply, error) {
	var out RechargeReply
	pattern := "/api/v1/billing/recharge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBillingServiceRecharge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationBillingInternalServiceCheckQuota = "/billing.v1.BillingInternalService/CheckQuota"
const OperationBillingInternalServiceDeductQuota = "/billing.v1.BillingInternalService/DeductQuota"
const OperationBillingInternalServiceRechargeCallback = "/billing.v1.BillingInternalService/RechargeCallback"

type BillingInternalServiceHTTPServer interface {
	// CheckQuota 检查并预扣费 (Check & Reserve)
	CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaReply, error)
	// DeductQuota 确认扣费 (Commit)
	DeductQuota(context.Context, *DeductQuotaRequest) (*DeductQuotaReply, error)
	// RechargeCallback 充值回调 (来自 Payment Service)
	RechargeCallback(context.Context, *RechargeCallbackRequest) (*RechargeCallbackReply, error)
}

func RegisterBillingInternalServiceHTTPServer(s *http.Server, srv BillingInternalServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/internal/v1/billing/check", _BillingInternalService_CheckQuota0_HTTP_Handler(srv))
	r.POST("/internal/v1/billing/deduct", _BillingInternalService_DeductQuota0_HTTP_Handler(srv))
	r.POST("/internal/v1/billing/callback", _BillingInternalService_RechargeCallback0_HTTP_Handler(srv))
}

func _BillingInternalService_CheckQuota0_HTTP_Handler(srv BillingInternalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckQuotaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingInternalServiceCheckQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckQuota(ctx, req.(*CheckQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckQuotaReply)
		return ctx.Result(200, reply)
	}
}

func _BillingInternalService_DeductQuota0_HTTP_Handler(srv BillingInternalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeductQuotaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingInternalServiceDeductQuota)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeductQuota(ctx, req.(*DeductQuotaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeductQuotaReply)
		return ctx.Result(200, reply)
	}
}

func _BillingInternalService_RechargeCallback0_HTTP_Handler(srv BillingInternalServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RechargeCallbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBillingInternalServiceRechargeCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RechargeCallback(ctx, req.(*RechargeCallbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RechargeCallbackReply)
		return ctx.Result(200, reply)
	}
}

type BillingInternalServiceHTTPClient interface {
	// CheckQuota 检查并预扣费 (Check & Reserve)
	CheckQuota(ctx context.Context, req *CheckQuotaRequest, opts ...http.CallOption) (rsp *CheckQuotaReply, err error)
	// DeductQuota 确认扣费 (Commit)
	DeductQuota(ctx context.Context, req *DeductQuotaRequest, opts ...http.CallOption) (rsp *DeductQuotaReply, err error)
	// RechargeCallback 充值回调 (来自 Payment Service)
	RechargeCallback(ctx context.Context, req *RechargeCallbackRequest, opts ...http.CallOption) (rsp *RechargeCallbackReply, err error)
}

type BillingInternalServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBillingInternalServiceHTTPClient(client *http.Client) BillingInternalServiceHTTPClient {
	return &BillingInternalServiceHTTPClientImpl{client}
}

// CheckQuota 检查并预扣费 (Check & Reserve)
func (c *BillingInternalServiceHTTPClientImpl) CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...http.CallOption) (*CheckQuotaReply, error) {
	var out CheckQuotaReply
	pattern := "/internal/v1/billing/check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBillingInternalServiceCheckQuota))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeductQuota 确认扣费 (Commit)
func (c *BillingInternalServiceHTTPClientImpl) DeductQuota(ctx context.Context, in *DeductQuotaRequest, opts ...http.CallOption) (*DeductQuotaReply, error) {
	var out DeductQuotaReply
	pattern := "/internal/v1/billing/deduct"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBillingInternalServiceDeductQuota))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RechargeCallback 充值回调 (来自 Payment Service)
func (c *BillingInternalServiceHTTPClientImpl) RechargeCallback(ctx context.Context, in *RechargeCallbackRequest, opts ...http.CallOption) (*RechargeCallbackReply, error) {
	var out RechargeCallbackReply
	pattern := "/internal/v1/billing/callback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBillingInternalServiceRechargeCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
