// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: billing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetAccount_FullMethodName      = "/billing.v1.BillingService/GetAccount"
	BillingService_Recharge_FullMethodName        = "/billing.v1.BillingService/Recharge"
	BillingService_ListRecords_FullMethodName     = "/billing.v1.BillingService/ListRecords"
	BillingService_GetStatsToday_FullMethodName   = "/billing.v1.BillingService/GetStatsToday"
	BillingService_GetStatsMonth_FullMethodName   = "/billing.v1.BillingService/GetStatsMonth"
	BillingService_GetStatsSummary_FullMethodName = "/billing.v1.BillingService/GetStatsSummary"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService 计费服务（外部接口）
// 面向前端/开发者的接口
type BillingServiceClient interface {
	// 获取账户资产信息 (余额 + 剩余配额)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountReply, error)
	// 发起充值 (返回支付链接)
	Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeReply, error)
	// 获取消费流水
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error)
	// 获取今日调用统计
	GetStatsToday(ctx context.Context, in *GetStatsTodayRequest, opts ...grpc.CallOption) (*GetStatsReply, error)
	// 获取本月调用统计
	GetStatsMonth(ctx context.Context, in *GetStatsMonthRequest, opts ...grpc.CallOption) (*GetStatsReply, error)
	// 获取汇总统计（所有服务）
	GetStatsSummary(ctx context.Context, in *GetStatsSummaryRequest, opts ...grpc.CallOption) (*GetStatsSummaryReply, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountReply)
	err := c.cc.Invoke(ctx, BillingService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RechargeReply)
	err := c.cc.Invoke(ctx, BillingService_Recharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsReply)
	err := c.cc.Invoke(ctx, BillingService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetStatsToday(ctx context.Context, in *GetStatsTodayRequest, opts ...grpc.CallOption) (*GetStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsReply)
	err := c.cc.Invoke(ctx, BillingService_GetStatsToday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetStatsMonth(ctx context.Context, in *GetStatsMonthRequest, opts ...grpc.CallOption) (*GetStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsReply)
	err := c.cc.Invoke(ctx, BillingService_GetStatsMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetStatsSummary(ctx context.Context, in *GetStatsSummaryRequest, opts ...grpc.CallOption) (*GetStatsSummaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsSummaryReply)
	err := c.cc.Invoke(ctx, BillingService_GetStatsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService 计费服务（外部接口）
// 面向前端/开发者的接口
type BillingServiceServer interface {
	// 获取账户资产信息 (余额 + 剩余配额)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountReply, error)
	// 发起充值 (返回支付链接)
	Recharge(context.Context, *RechargeRequest) (*RechargeReply, error)
	// 获取消费流水
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsReply, error)
	// 获取今日调用统计
	GetStatsToday(context.Context, *GetStatsTodayRequest) (*GetStatsReply, error)
	// 获取本月调用统计
	GetStatsMonth(context.Context, *GetStatsMonthRequest) (*GetStatsReply, error)
	// 获取汇总统计（所有服务）
	GetStatsSummary(context.Context, *GetStatsSummaryRequest) (*GetStatsSummaryReply, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedBillingServiceServer) Recharge(context.Context, *RechargeRequest) (*RechargeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Recharge not implemented")
}
func (UnimplementedBillingServiceServer) ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedBillingServiceServer) GetStatsToday(context.Context, *GetStatsTodayRequest) (*GetStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsToday not implemented")
}
func (UnimplementedBillingServiceServer) GetStatsMonth(context.Context, *GetStatsMonthRequest) (*GetStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsMonth not implemented")
}
func (UnimplementedBillingServiceServer) GetStatsSummary(context.Context, *GetStatsSummaryRequest) (*GetStatsSummaryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsSummary not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_Recharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).Recharge(ctx, req.(*RechargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetStatsToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsTodayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetStatsToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetStatsToday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetStatsToday(ctx, req.(*GetStatsTodayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetStatsMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetStatsMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetStatsMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetStatsMonth(ctx, req.(*GetStatsMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetStatsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetStatsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetStatsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetStatsSummary(ctx, req.(*GetStatsSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _BillingService_GetAccount_Handler,
		},
		{
			MethodName: "Recharge",
			Handler:    _BillingService_Recharge_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _BillingService_ListRecords_Handler,
		},
		{
			MethodName: "GetStatsToday",
			Handler:    _BillingService_GetStatsToday_Handler,
		},
		{
			MethodName: "GetStatsMonth",
			Handler:    _BillingService_GetStatsMonth_Handler,
		},
		{
			MethodName: "GetStatsSummary",
			Handler:    _BillingService_GetStatsSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}

const (
	BillingInternalService_CheckQuota_FullMethodName       = "/billing.v1.BillingInternalService/CheckQuota"
	BillingInternalService_DeductQuota_FullMethodName      = "/billing.v1.BillingInternalService/DeductQuota"
	BillingInternalService_RechargeCallback_FullMethodName = "/billing.v1.BillingInternalService/RechargeCallback"
)

// BillingInternalServiceClient is the client API for BillingInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingInternalService 计费内部服务（内部接口）
// 面向内部服务（Gateway/Payment）的接口
type BillingInternalServiceClient interface {
	// 检查并预扣费 (Check & Reserve)
	CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaReply, error)
	// 确认扣费 (Commit)
	DeductQuota(ctx context.Context, in *DeductQuotaRequest, opts ...grpc.CallOption) (*DeductQuotaReply, error)
	// 充值回调 (来自 Payment Service)
	RechargeCallback(ctx context.Context, in *RechargeCallbackRequest, opts ...grpc.CallOption) (*RechargeCallbackReply, error)
}

type billingInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingInternalServiceClient(cc grpc.ClientConnInterface) BillingInternalServiceClient {
	return &billingInternalServiceClient{cc}
}

func (c *billingInternalServiceClient) CheckQuota(ctx context.Context, in *CheckQuotaRequest, opts ...grpc.CallOption) (*CheckQuotaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckQuotaReply)
	err := c.cc.Invoke(ctx, BillingInternalService_CheckQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingInternalServiceClient) DeductQuota(ctx context.Context, in *DeductQuotaRequest, opts ...grpc.CallOption) (*DeductQuotaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductQuotaReply)
	err := c.cc.Invoke(ctx, BillingInternalService_DeductQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingInternalServiceClient) RechargeCallback(ctx context.Context, in *RechargeCallbackRequest, opts ...grpc.CallOption) (*RechargeCallbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RechargeCallbackReply)
	err := c.cc.Invoke(ctx, BillingInternalService_RechargeCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingInternalServiceServer is the server API for BillingInternalService service.
// All implementations must embed UnimplementedBillingInternalServiceServer
// for forward compatibility.
//
// BillingInternalService 计费内部服务（内部接口）
// 面向内部服务（Gateway/Payment）的接口
type BillingInternalServiceServer interface {
	// 检查并预扣费 (Check & Reserve)
	CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaReply, error)
	// 确认扣费 (Commit)
	DeductQuota(context.Context, *DeductQuotaRequest) (*DeductQuotaReply, error)
	// 充值回调 (来自 Payment Service)
	RechargeCallback(context.Context, *RechargeCallbackRequest) (*RechargeCallbackReply, error)
	mustEmbedUnimplementedBillingInternalServiceServer()
}

// UnimplementedBillingInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingInternalServiceServer struct{}

func (UnimplementedBillingInternalServiceServer) CheckQuota(context.Context, *CheckQuotaRequest) (*CheckQuotaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckQuota not implemented")
}
func (UnimplementedBillingInternalServiceServer) DeductQuota(context.Context, *DeductQuotaRequest) (*DeductQuotaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductQuota not implemented")
}
func (UnimplementedBillingInternalServiceServer) RechargeCallback(context.Context, *RechargeCallbackRequest) (*RechargeCallbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RechargeCallback not implemented")
}
func (UnimplementedBillingInternalServiceServer) mustEmbedUnimplementedBillingInternalServiceServer() {
}
func (UnimplementedBillingInternalServiceServer) testEmbeddedByValue() {}

// UnsafeBillingInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingInternalServiceServer will
// result in compilation errors.
type UnsafeBillingInternalServiceServer interface {
	mustEmbedUnimplementedBillingInternalServiceServer()
}

func RegisterBillingInternalServiceServer(s grpc.ServiceRegistrar, srv BillingInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingInternalService_ServiceDesc, srv)
}

func _BillingInternalService_CheckQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingInternalServiceServer).CheckQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingInternalService_CheckQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingInternalServiceServer).CheckQuota(ctx, req.(*CheckQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingInternalService_DeductQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingInternalServiceServer).DeductQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingInternalService_DeductQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingInternalServiceServer).DeductQuota(ctx, req.(*DeductQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingInternalService_RechargeCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingInternalServiceServer).RechargeCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingInternalService_RechargeCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingInternalServiceServer).RechargeCallback(ctx, req.(*RechargeCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingInternalService_ServiceDesc is the grpc.ServiceDesc for BillingInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.BillingInternalService",
	HandlerType: (*BillingInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckQuota",
			Handler:    _BillingInternalService_CheckQuota_Handler,
		},
		{
			MethodName: "DeductQuota",
			Handler:    _BillingInternalService_DeductQuota_Handler,
		},
		{
			MethodName: "RechargeCallback",
			Handler:    _BillingInternalService_RechargeCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
