// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: billing.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAccountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Quotas        []*FreeQuota           `protobuf:"bytes,3,rep,name=quotas,proto3" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReply) Reset() {
	*x = GetAccountReply{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReply) ProtoMessage() {}

func (x *GetAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReply.ProtoReflect.Descriptor instead.
func (*GetAccountReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAccountReply) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountReply) GetQuotas() []*FreeQuota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

type FreeQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TotalQuota    int32                  `protobuf:"varint,2,opt,name=total_quota,json=totalQuota,proto3" json:"total_quota,omitempty"`
	UsedQuota     int32                  `protobuf:"varint,3,opt,name=used_quota,json=usedQuota,proto3" json:"used_quota,omitempty"`
	ResetMonth    string                 `protobuf:"bytes,4,opt,name=reset_month,json=resetMonth,proto3" json:"reset_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeQuota) Reset() {
	*x = FreeQuota{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeQuota) ProtoMessage() {}

func (x *FreeQuota) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeQuota.ProtoReflect.Descriptor instead.
func (*FreeQuota) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *FreeQuota) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FreeQuota) GetTotalQuota() int32 {
	if x != nil {
		return x.TotalQuota
	}
	return 0
}

func (x *FreeQuota) GetUsedQuota() int32 {
	if x != nil {
		return x.UsedQuota
	}
	return 0
}

func (x *FreeQuota) GetResetMonth() string {
	if x != nil {
		return x.ResetMonth
	}
	return ""
}

type RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // wechat, alipay
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                // 币种，必填，例如：CNY, USD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *RechargeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RechargeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *RechargeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RechargeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeReply) Reset() {
	*x = RechargeReply{}
	mi := &file_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReply) ProtoMessage() {}

func (x *RechargeReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReply.ProtoReflect.Descriptor instead.
func (*RechargeReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{4}
}

func (x *RechargeReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RechargeReply) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ListRecordsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRecordsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BillingRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsReply) Reset() {
	*x = ListRecordsReply{}
	mi := &file_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsReply) ProtoMessage() {}

func (x *ListRecordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsReply.ProtoReflect.Descriptor instead.
func (*ListRecordsReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ListRecordsReply) GetRecords() []*BillingRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BillingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 1:免费额度, 2:余额扣费
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingRecord) Reset() {
	*x = BillingRecord{}
	mi := &file_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingRecord) ProtoMessage() {}

func (x *BillingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingRecord.ProtoReflect.Descriptor instead.
func (*BillingRecord) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{7}
}

func (x *BillingRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillingRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BillingRecord) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BillingRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillingRecord) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BillingRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CheckQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaRequest) Reset() {
	*x = CheckQuotaRequest{}
	mi := &file_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaRequest) ProtoMessage() {}

func (x *CheckQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{8}
}

func (x *CheckQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckQuotaRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CheckQuotaRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CheckQuotaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaReply) Reset() {
	*x = CheckQuotaReply{}
	mi := &file_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaReply) ProtoMessage() {}

func (x *CheckQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaReply.ProtoReflect.Descriptor instead.
func (*CheckQuotaReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{9}
}

func (x *CheckQuotaReply) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckQuotaReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeductQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Cost          float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductQuotaRequest) Reset() {
	*x = DeductQuotaRequest{}
	mi := &file_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductQuotaRequest) ProtoMessage() {}

func (x *DeductQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductQuotaRequest.ProtoReflect.Descriptor instead.
func (*DeductQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{10}
}

func (x *DeductQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductQuotaRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeductQuotaRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DeductQuotaRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type DeductQuotaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductQuotaReply) Reset() {
	*x = DeductQuotaReply{}
	mi := &file_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductQuotaReply) ProtoMessage() {}

func (x *DeductQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductQuotaReply.ProtoReflect.Descriptor instead.
func (*DeductQuotaReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{11}
}

func (x *DeductQuotaReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductQuotaReply) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type RechargeCallbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentOrderId string                 `protobuf:"bytes,2,opt,name=payment_order_id,json=paymentOrderId,proto3" json:"payment_order_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RechargeCallbackRequest) Reset() {
	*x = RechargeCallbackRequest{}
	mi := &file_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeCallbackRequest) ProtoMessage() {}

func (x *RechargeCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeCallbackRequest.ProtoReflect.Descriptor instead.
func (*RechargeCallbackRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{12}
}

func (x *RechargeCallbackRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RechargeCallbackRequest) GetPaymentOrderId() string {
	if x != nil {
		return x.PaymentOrderId
	}
	return ""
}

func (x *RechargeCallbackRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RechargeCallbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeCallbackReply) Reset() {
	*x = RechargeCallbackReply{}
	mi := &file_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeCallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeCallbackReply) ProtoMessage() {}

func (x *RechargeCallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeCallbackReply.ProtoReflect.Descriptor instead.
func (*RechargeCallbackReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{13}
}

func (x *RechargeCallbackReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 统计相关消息
type GetStatsTodayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 可选，不传则统计所有服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsTodayRequest) Reset() {
	*x = GetStatsTodayRequest{}
	mi := &file_billing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsTodayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsTodayRequest) ProtoMessage() {}

func (x *GetStatsTodayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsTodayRequest.ProtoReflect.Descriptor instead.
func (*GetStatsTodayRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsTodayRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatsTodayRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetStatsMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 可选，不传则统计所有服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsMonthRequest) Reset() {
	*x = GetStatsMonthRequest{}
	mi := &file_billing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsMonthRequest) ProtoMessage() {}

func (x *GetStatsMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsMonthRequest.ProtoReflect.Descriptor instead.
func (*GetStatsMonthRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsMonthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatsMonthRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetStatsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsSummaryRequest) Reset() {
	*x = GetStatsSummaryRequest{}
	mi := &file_billing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsSummaryRequest) ProtoMessage() {}

func (x *GetStatsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetStatsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 如果请求时指定了服务名称，这里返回；否则为空
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`   // 总调用次数
	TotalCost     float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`     // 总费用（仅余额扣费部分）
	FreeCount     int32                  `protobuf:"varint,5,opt,name=free_count,json=freeCount,proto3" json:"free_count,omitempty"`      // 免费额度使用次数
	PaidCount     int32                  `protobuf:"varint,6,opt,name=paid_count,json=paidCount,proto3" json:"paid_count,omitempty"`      // 余额扣费次数
	Period        string                 `protobuf:"bytes,7,opt,name=period,proto3" json:"period,omitempty"`                              // 统计周期：today 或 month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReply) Reset() {
	*x = GetStatsReply{}
	mi := &file_billing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReply) ProtoMessage() {}

func (x *GetStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReply.ProtoReflect.Descriptor instead.
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatsReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatsReply) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetStatsReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetStatsReply) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GetStatsReply) GetFreeCount() int32 {
	if x != nil {
		return x.FreeCount
	}
	return 0
}

func (x *GetStatsReply) GetPaidCount() int32 {
	if x != nil {
		return x.PaidCount
	}
	return 0
}

func (x *GetStatsReply) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type ServiceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`   // 总调用次数
	TotalCost     float64                `protobuf:"fixed64,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`     // 总费用
	FreeCount     int32                  `protobuf:"varint,4,opt,name=free_count,json=freeCount,proto3" json:"free_count,omitempty"`      // 免费额度使用次数
	PaidCount     int32                  `protobuf:"varint,5,opt,name=paid_count,json=paidCount,proto3" json:"paid_count,omitempty"`      // 余额扣费次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStats) Reset() {
	*x = ServiceStats{}
	mi := &file_billing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStats) ProtoMessage() {}

func (x *ServiceStats) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStats.ProtoReflect.Descriptor instead.
func (*ServiceStats) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceStats) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceStats) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ServiceStats) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ServiceStats) GetFreeCount() int32 {
	if x != nil {
		return x.FreeCount
	}
	return 0
}

func (x *ServiceStats) GetPaidCount() int32 {
	if x != nil {
		return x.PaidCount
	}
	return 0
}

type GetStatsSummaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 所有服务总调用次数
	TotalCost     float64                `protobuf:"fixed64,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`   // 所有服务总费用
	Services      []*ServiceStats        `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`                        // 各服务统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsSummaryReply) Reset() {
	*x = GetStatsSummaryReply{}
	mi := &file_billing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsSummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsSummaryReply) ProtoMessage() {}

func (x *GetStatsSummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsSummaryReply.ProtoReflect.Descriptor instead.
func (*GetStatsSummaryReply) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{19}
}

func (x *GetStatsSummaryReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatsSummaryReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetStatsSummaryReply) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GetStatsSummaryReply) GetServices() []*ServiceStats {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\n" +
	"billing.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x11GetAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"s\n" +
	"\x0fGetAccountReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12-\n" +
	"\x06quotas\x18\x03 \x03(\v2\x15.billing.v1.FreeQuotaR\x06quotas\"\x8f\x01\n" +
	"\tFreeQuota\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vtotal_quota\x18\x02 \x01(\x05R\n" +
	"totalQuota\x12\x1d\n" +
	"\n" +
	"used_quota\x18\x03 \x01(\x05R\tusedQuota\x12\x1f\n" +
	"\vreset_month\x18\x04 \x01(\tR\n" +
	"resetMonth\"\x85\x01\n" +
	"\x0fRechargeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"K\n" +
	"\rRechargeReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\"^\n" +
	"\x12ListRecordsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"]\n" +
	"\x10ListRecordsReply\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.billing.v1.BillingRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xbf\x01\n" +
	"\rBillingRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x11CheckQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"C\n" +
	"\x0fCheckQuotaReply\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"z\n" +
	"\x12DeductQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\"I\n" +
	"\x10DeductQuotaReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\"\x8e\x01\n" +
	"\x17RechargeCallbackRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\x10payment_order_id\x18\x02 \x01(\tR\x0epaymentOrderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"1\n" +
	"\x15RechargeCallbackReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x14GetStatsTodayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"R\n" +
	"\x14GetStatsMonthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"1\n" +
	"\x16GetStatsSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\rGetStatsReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x1d\n" +
	"\n" +
	"free_count\x18\x05 \x01(\x05R\tfreeCount\x12\x1d\n" +
	"\n" +
	"paid_count\x18\x06 \x01(\x05R\tpaidCount\x12\x16\n" +
	"\x06period\x18\a \x01(\tR\x06period\"\xaf\x01\n" +
	"\fServiceStats\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x01R\ttotalCost\x12\x1d\n" +
	"\n" +
	"free_count\x18\x04 \x01(\x05R\tfreeCount\x12\x1d\n" +
	"\n" +
	"paid_count\x18\x05 \x01(\x05R\tpaidCount\"\xa5\x01\n" +
	"\x14GetStatsSummaryReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x01R\ttotalCost\x124\n" +
	"\bservices\x18\x04 \x03(\v2\x18.billing.v1.ServiceStatsR\bservices2\xb8\x05\n" +
	"\x0eBillingService\x12i\n" +
	"\n" +
	"GetAccount\x12\x1d.billing.v1.GetAccountRequest\x1a\x1b.billing.v1.GetAccountReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/billing/account\x12g\n" +
	"\bRecharge\x12\x1b.billing.v1.RechargeRequest\x1a\x19.billing.v1.RechargeReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/billing/recharge\x12l\n" +
	"\vListRecords\x12\x1e.billing.v1.ListRecordsRequest\x1a\x1c.billing.v1.ListRecordsReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/billing/records\x12q\n" +
	"\rGetStatsToday\x12 .billing.v1.GetStatsTodayRequest\x1a\x19.billing.v1.GetStatsReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/billing/stats/today\x12q\n" +
	"\rGetStatsMonth\x12 .billing.v1.GetStatsMonthRequest\x1a\x19.billing.v1.GetStatsReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/billing/stats/month\x12~\n" +
	"\x0fGetStatsSummary\x12\".billing.v1.GetStatsSummaryRequest\x1a .billing.v1.GetStatsSummaryReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/billing/stats/summary2\x85\x03\n" +
	"\x16BillingInternalService\x12o\n" +
	"\n" +
	"CheckQuota\x12\x1d.billing.v1.CheckQuotaRequest\x1a\x1b.billing.v1.CheckQuotaReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/internal/v1/billing/check\x12s\n" +
	"\vDeductQuota\x12\x1e.billing.v1.DeductQuotaRequest\x1a\x1c.billing.v1.DeductQuotaReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/internal/v1/billing/deduct\x12\x84\x01\n" +
	"\x10RechargeCallback\x12#.billing.v1.RechargeCallbackRequest\x1a!.billing.v1.RechargeCallbackReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/internal/v1/billing/callbackB#Z!billing-service/api/billing/v1;v1b\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_billing_proto_goTypes = []any{
	(*GetAccountRequest)(nil),       // 0: billing.v1.GetAccountRequest
	(*GetAccountReply)(nil),         // 1: billing.v1.GetAccountReply
	(*FreeQuota)(nil),               // 2: billing.v1.FreeQuota
	(*RechargeRequest)(nil),         // 3: billing.v1.RechargeRequest
	(*RechargeReply)(nil),           // 4: billing.v1.RechargeReply
	(*ListRecordsRequest)(nil),      // 5: billing.v1.ListRecordsRequest
	(*ListRecordsReply)(nil),        // 6: billing.v1.ListRecordsReply
	(*BillingRecord)(nil),           // 7: billing.v1.BillingRecord
	(*CheckQuotaRequest)(nil),       // 8: billing.v1.CheckQuotaRequest
	(*CheckQuotaReply)(nil),         // 9: billing.v1.CheckQuotaReply
	(*DeductQuotaRequest)(nil),      // 10: billing.v1.DeductQuotaRequest
	(*DeductQuotaReply)(nil),        // 11: billing.v1.DeductQuotaReply
	(*RechargeCallbackRequest)(nil), // 12: billing.v1.RechargeCallbackRequest
	(*RechargeCallbackReply)(nil),   // 13: billing.v1.RechargeCallbackReply
	(*GetStatsTodayRequest)(nil),    // 14: billing.v1.GetStatsTodayRequest
	(*GetStatsMonthRequest)(nil),    // 15: billing.v1.GetStatsMonthRequest
	(*GetStatsSummaryRequest)(nil),  // 16: billing.v1.GetStatsSummaryRequest
	(*GetStatsReply)(nil),           // 17: billing.v1.GetStatsReply
	(*ServiceStats)(nil),            // 18: billing.v1.ServiceStats
	(*GetStatsSummaryReply)(nil),    // 19: billing.v1.GetStatsSummaryReply
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
}
var file_billing_proto_depIdxs = []int32{
	2,  // 0: billing.v1.GetAccountReply.quotas:type_name -> billing.v1.FreeQuota
	7,  // 1: billing.v1.ListRecordsReply.records:type_name -> billing.v1.BillingRecord
	20, // 2: billing.v1.BillingRecord.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: billing.v1.GetStatsSummaryReply.services:type_name -> billing.v1.ServiceStats
	0,  // 4: billing.v1.BillingService.GetAccount:input_type -> billing.v1.GetAccountRequest
	3,  // 5: billing.v1.BillingService.Recharge:input_type -> billing.v1.RechargeRequest
	5,  // 6: billing.v1.BillingService.ListRecords:input_type -> billing.v1.ListRecordsRequest
	14, // 7: billing.v1.BillingService.GetStatsToday:input_type -> billing.v1.GetStatsTodayRequest
	15, // 8: billing.v1.BillingService.GetStatsMonth:input_type -> billing.v1.GetStatsMonthRequest
	16, // 9: billing.v1.BillingService.GetStatsSummary:input_type -> billing.v1.GetStatsSummaryRequest
	8,  // 10: billing.v1.BillingInternalService.CheckQuota:input_type -> billing.v1.CheckQuotaRequest
	10, // 11: billing.v1.BillingInternalService.DeductQuota:input_type -> billing.v1.DeductQuotaRequest
	12, // 12: billing.v1.BillingInternalService.RechargeCallback:input_type -> billing.v1.RechargeCallbackRequest
	1,  // 13: billing.v1.BillingService.GetAccount:output_type -> billing.v1.GetAccountReply
	4,  // 14: billing.v1.BillingService.Recharge:output_type -> billing.v1.RechargeReply
	6,  // 15: billing.v1.BillingService.ListRecords:output_type -> billing.v1.ListRecordsReply
	17, // 16: billing.v1.BillingService.GetStatsToday:output_type -> billing.v1.GetStatsReply
	17, // 17: billing.v1.BillingService.GetStatsMonth:output_type -> billing.v1.GetStatsReply
	19, // 18: billing.v1.BillingService.GetStatsSummary:output_type -> billing.v1.GetStatsSummaryReply
	9,  // 19: billing.v1.BillingInternalService.CheckQuota:output_type -> billing.v1.CheckQuotaReply
	11, // 20: billing.v1.BillingInternalService.DeductQuota:output_type -> billing.v1.DeductQuotaReply
	13, // 21: billing.v1.BillingInternalService.RechargeCallback:output_type -> billing.v1.RechargeCallbackReply
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
