// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/biz"
	"billing-service/internal/conf"
	"billing-service/internal/data"
	"github.com/go-kratos/kratos/v2/log"
	"os"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 初始化应用
func wireApp(bootstrap *conf.Bootstrap) (*CronApp, func(), error) {
	confData := bootstrap.Data
	logger := newLogger()
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	billingRepo := data.NewBillingRepo(dataData, logger)
	billingConfig := biz.NewBillingConfig(bootstrap)
	billingUseCase := biz.NewBillingUseCase(billingRepo, logger, billingConfig)
	cronApp := &CronApp{
		billingUsecase: billingUseCase,
	}
	return cronApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// CronApp Cron 应用结构
type CronApp struct {
	billingUsecase *biz.BillingUseCase
}

// newLogger 创建 logger
func newLogger() log.Logger {
	return log.With(log.NewStdLogger(os.Stdout), "ts", log.DefaultTimestamp, "caller", log.DefaultCaller, "service.name", "billing-cron")
}
