// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/biz"
	"billing-service/internal/conf"
	"billing-service/internal/data"
	"github.com/go-kratos/kratos/v2/log"
	"os"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 初始化应用
func wireApp(bootstrap *conf.Bootstrap) (*CronApp, func(), error) {
	confData := bootstrap.Data
	logger := newLogger()
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userBalanceRepo := data.NewUserBalanceRepo(dataData, logger)
	userBalanceUseCase := biz.NewUserBalanceUseCase(userBalanceRepo, logger)
	freeQuotaRepo := data.NewFreeQuotaRepo(dataData, logger)
	billingConfig := biz.NewBillingConfig(bootstrap)
	freeQuotaUseCase := biz.NewFreeQuotaUseCase(freeQuotaRepo, billingConfig, logger)
	billingRecordRepo := data.NewBillingRecordRepo(dataData, logger)
	billingRecordUseCase := biz.NewBillingRecordUseCase(billingRecordRepo, logger)
	rechargeOrderRepo := data.NewRechargeOrderRepo(dataData, logger)
	paymentService := bootstrap.PaymentService
	paymentServiceClient, err := data.NewPaymentServiceClient(paymentService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rechargeOrderUseCase := biz.NewRechargeOrderUseCase(rechargeOrderRepo, paymentServiceClient, billingConfig, logger)
	statsRepo := data.NewStatsRepo(dataData, logger)
	statsUseCase := biz.NewStatsUseCase(statsRepo, logger)
	redsync := data.NewRedSync(dataData)
	billingRepo := data.NewBillingRepo(dataData, redsync, logger, userBalanceRepo, freeQuotaRepo, billingRecordRepo, rechargeOrderRepo, statsRepo)
	billingUseCase := biz.NewBillingUseCase(userBalanceUseCase, freeQuotaUseCase, billingRecordUseCase, rechargeOrderUseCase, statsUseCase, billingRepo, billingConfig, logger)
	cronApp := &CronApp{
		billingUsecase: billingUseCase,
	}
	return cronApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// CronApp Cron 应用结构
type CronApp struct {
	billingUsecase *biz.BillingUseCase
}

// newLogger 创建 logger
func newLogger() log.Logger {
	return log.With(log.NewStdLogger(os.Stdout), "ts", log.DefaultTimestamp, "caller", log.DefaultCaller, "service.name", "billing-cron")
}
