// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/biz"
	"billing-service/internal/conf"
	"billing-service/internal/data"
	"billing-service/internal/server"
	"billing-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRedis(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	billingRepo := data.NewBillingRepo(dataData, logger)
	billingConfig := biz.NewBillingConfig(bootstrap)
	billingUseCase := biz.NewBillingUseCase(billingRepo, logger, billingConfig)
	billingService := service.NewBillingService(billingUseCase, logger)
	billingInternalService := service.NewBillingInternalService(billingUseCase, logger)
	grpcServer := server.NewGRPCServer(bootstrap, billingService, billingInternalService)
	httpServer := server.NewHTTPServer(bootstrap, billingService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
