// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/biz"
	"billing-service/internal/conf"
	"billing-service/internal/data"
	"billing-service/internal/server"
	"billing-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	billingRepo := data.NewBillingRepo(dataData, logger)
	billingConfig := biz.NewBillingConfig(bootstrap)
	billingUseCase := biz.NewBillingUseCase(billingRepo, logger, billingConfig)
	billingService := service.NewBillingService(billingUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, billingService, logger)
	httpServer := server.NewHTTPServer(confServer, billingService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
