// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/biz"
	"billing-service/internal/conf"
	"billing-service/internal/data"
	"billing-service/internal/server"
	"billing-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userBalanceRepo := data.NewUserBalanceRepo(dataData, logger)
	userBalanceUseCase := biz.NewUserBalanceUseCase(userBalanceRepo, logger)
	freeQuotaRepo := data.NewFreeQuotaRepo(dataData, logger)
	billingConfig := biz.NewBillingConfig(bootstrap)
	freeQuotaUseCase := biz.NewFreeQuotaUseCase(freeQuotaRepo, billingConfig, logger)
	billingRecordRepo := data.NewBillingRecordRepo(dataData, logger)
	billingRecordUseCase := biz.NewBillingRecordUseCase(billingRecordRepo, logger)
	rechargeOrderRepo := data.NewRechargeOrderRepo(dataData, logger)
	paymentService := bootstrap.PaymentService
	paymentServiceClient, err := data.NewPaymentServiceClient(paymentService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rechargeOrderUseCase := biz.NewRechargeOrderUseCase(rechargeOrderRepo, paymentServiceClient, billingConfig, logger)
	statsRepo := data.NewStatsRepo(dataData, logger)
	statsUseCase := biz.NewStatsUseCase(statsRepo, logger)
	redsync := data.NewRedSync(dataData)
	billingRepo := data.NewBillingRepo(dataData, redsync, logger, userBalanceRepo, freeQuotaRepo, billingRecordRepo, rechargeOrderRepo, statsRepo)
	billingUseCase := biz.NewBillingUseCase(userBalanceUseCase, freeQuotaUseCase, billingRecordUseCase, rechargeOrderUseCase, statsUseCase, billingRepo, billingConfig, logger)
	billingService := service.NewBillingService(billingUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, billingService, logger)
	httpServer := server.NewHTTPServer(confServer, billingService, logger)
	mqConsumerServer := server.NewMQConsumerServer(confData, billingRepo, logger)
	app := newApp(logger, grpcServer, httpServer, mqConsumerServer)
	return app, func() {
		cleanup()
	}, nil
}
